# Generated by Django 4.0.4 on 2022-05-06 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelterName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('website', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelters', to='petpursuit.state')),
            ],
        ),
        migrations.CreateModel(
            name='Feline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.TextField()),
                ('location', models.TextField()),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='felines', to='petpursuit.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='Canine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogName', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.TextField()),
                ('location', models.TextField()),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canines', to='petpursuit.shelter')),
            ],
        ),
    ]
