# Generated by Django 4.0.4 on 2022-05-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petpursuit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canine',
            name='dogName',
            field=models.CharField(default='canine_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='canine',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canines', to='petpursuit.shelter'),
        ),
        migrations.AlterField(
            model_name='feline',
            name='catName',
            field=models.CharField(default='feline_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='feline',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='felines', to='petpursuit.shelter'),
        ),
    ]
