# Generated by Django 4.0.4 on 2022-05-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpursuit', '0002_alter_canine_dogname_alter_canine_shelter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canine',
            name='location',
        ),
        migrations.RemoveField(
            model_name='feline',
            name='location',
        ),
        migrations.AlterField(
            model_name='canine',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='canine',
            name='dogName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feline',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='feline',
            name='catName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
