# Generated by Django 4.0.4 on 2022-05-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpursuit', '0003_remove_canine_location_remove_feline_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='location',
        ),
        migrations.AddField(
            model_name='canine',
            name='photo_url',
            field=models.CharField(default='no dice!', max_length=200),
        ),
        migrations.AddField(
            model_name='feline',
            name='photo_url',
            field=models.CharField(default='no dice!', max_length=200),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
