# Generated by Django 4.0.4 on 2022-05-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpursuit', '0011_alter_canine_user_alter_feline_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canine',
            name='photo_url',
            field=models.CharField(default='no dice!', max_length=400),
        ),
        migrations.AlterField(
            model_name='feline',
            name='photo_url',
            field=models.CharField(default='no dice!', max_length=400),
        ),
    ]
